### ISSUE TITLE
Build Error on Windows 10: Looping path name makes filename too long

### ISSUE THREAD

**Issue by aaronliu0130** [CatBlock/catblock#170]
#### Answer these questions to help us solve the case!
(If you have a problem that isn't a bug, or want to suggest a feature, do so at <http://support.getcatblock.com>

#### 1. List some steps we can follow to make the bug happen on our end.

1. Download `catblock_master.zip` from github
2. `cd` into the root directory using command prompt
3. `python3 tools/make_release.py -b chrome -ext browser`

#### 2. When you followed these steps above, what did you think should happen?

CatBlock should've been built succesfully.

#### 3. What actually happened instead?

```batch-file
C:\Users\aaron\catblock-master>python3 tools/make_release.py -b chrome -ext browser
File not found - '*.DS_Store'
Generating browser package for chrome...
 > Generating CatBlock for Chrome...Traceback (most recent call last):
  File "tools/make_release.py", line 298, in <module>
    main()
  File "tools/make_release.py", line 289, in main
    generateBrowserPackage(args.browser)
  File "tools/make_release.py", line 228, in generateBrowserPackage
    shutil.copytree(os.getcwd(), BROWSER_PATH, ignore=shutil.ignore_patterns(".*", "builds", "tools"))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.240.0_x64__qbz5n2kfra8p0\lib\shutil.py", line 547, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.240.0_x64__qbz5n2kfra8p0\lib\shutil.py", line 504, in _copytree
    raise Error(errors)
shutil.Error: [('C:\\Users\\aaron\\catblock-master\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\background_safari.html', 'catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\background_safari.html', "[Errno 2] No such file or directory: 'catblock_chrome\\\\catblock_chrome\\\\catblock_chrome\\\\catblock_chrome\\\\catblock_chrome\\\\catblock_chrome\\\\catblock_chrome\\\\catblock_chrome\\\\catblock_chrome\\\\catblock_chrome\\\\catblock_chrome\\\\catblock_chrome\\\\catblock_chrome\\\\background_safari.html'"), ('C:\\Users\\aaron\\catblock-master\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock\\contentscript.js', 'catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock\\contentscript.js', "[Errno 2] No such file or directory: 'catblock_chrome\\\\catblock_chrome\\\\catblock_chrome\\\\catblock_chrome\\\\catblock_chrome\\\\catblock_chrome\\\\catblock_chrome\\\\catblock_chrome\\\\catblock_chrome\\\\catblock_chrome\\\\catblock_chrome\\\\catblock_chrome\\\\catblock_chrome\\\\catblock\\\\contentscript.js'"), ('C:\\Users\\aaron\\catblock-master\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock\\pix', 'catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock\\pix', "[WinError 206] The filename or extension is too long: 'catblock_chrome\\\\catblock_chrome\\\\catblock_chrome\\\\catblock_chrome\\\\catblock_chrome\\\\catblock_chrome\\\\catblock_chrome\\\\catblock_chrome\\\\catblock_chrome\\\\catblock_chrome\\\\catblock_chrome\\\\catblock_chrome\\\\catblock_chrome\\\\catblock\\\\pix'"), ('C:\\Users\\aaron\\catblock-master\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome', 'catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome\\catblock_chrome', "[WinError 206] The filename or extension is too long: 'catblock_chrome\\\\catblock_chrome\\\\catblock_chrome\\\\catblock_chrome\\\\catblock_chrome\\\\catblock_chrome\\\\catblock_chrome\\\\catblock_chrome\\\\catblock_chrome\\\\catblock_chrome\\\\catblock_chrome\\\\catblock_chrome\\\\catblock_chrome\\\\catblock_chrome'")]
```

#### 4. Finally, click the CatBlock button, then Options, then Support on the page that appears. Provide us with the **debug info** from that page.

![image](https://user-images.githubusercontent.com/11874211/67764185-5fb78300-fa84-11e9-97d4-4a218e2955f2.png)
![image](https://user-images.githubusercontent.com/11874211/67764244-7e1d7e80-fa84-11e9-9947-d6ebcfd27916.png)
![image](https://user-images.githubusercontent.com/11874211/67764300-9d1c1080-fa84-11e9-9f50-132445e8c4c1.png)
<img width="506" alt="ice_screenshot_20191029-194618" src="https://user-images.githubusercontent.com/11874211/67764387-cdfc4580-fa84-11e9-9ec7-ef7112093273.png">
```
<Copy and paste it over this line.>
```

#### 5. Any other information you think might be useful for us to know?

This is a build error.

**Comment by aaronliu0130** [comment]
What, it still hasn't been seen? I'll try to do it myself then.

**Comment by aaronliu0130** [comment]
This seems to be somewhat of an internal error.
